# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0

    id: "boxwallet"
    main: ./cmd/cli/main.go

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      #- goos: linux
      #  goarch: 386

  - id: "bwupdater"
    main: ./cmd/updater/main.go
    binary: "bwupdater"

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      #- goos: linux
      #  goarch: 386

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
      arm: arm32bit
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
#snapcrafts:
#  -
#    id: "boxwallet"
#    grade: stable
#    confinement: strict
#    base: bare
#    apps:
#      boxwallet:
#        plugs: ["personal-files"]
#    summary: BoxWallet is a multi-coin CLI tool, that gets your coin-of-choice wallet/node running fast, with just a few commands.
#    plugs:
#      dot-divi:
#        interface: personal-files
#        read:
#          - $HOME/.divi
#        write:
#          - $HOME/.divi
#
##      personal-files:
##        read:
##          - $HOME/.divi
##        write:
##          - $HOME/.divi
#    publish: false # <- this line for publish
#    description: |
#      BoxWallet is a single binary multi-coin CLI tool, that gets your coin-of-choice wallet/node set-up fast with just a few commands:
#
#      boxwallet coin - allows you to choose your coin of choice, which then downloads the projects core files from their official website and installs them automatically.
#
#      boxwallet start - starts the coin's daemon, which syncs the Blockchain.
#
#      boxwallet dash - displays a dashboard with the coins Blockchain and wallet info.
