package models

// ZANOGetInfo - The Main struct
type ZANOGetInfo struct {
	ID      string `json:"id"`
	Jsonrpc string `json:"jsonrpc"`
	Result  struct {
		AliasCount                 int    `json:"alias_count"`
		AltBlocksCount             int    `json:"alt_blocks_count"`
		BlockReward                int    `json:"block_reward"`
		CurrentBlocksMedian        int    `json:"current_blocks_median"`
		CurrentMaxAllowedBlockSize int    `json:"current_max_allowed_block_size"`
		CurrentNetworkHashrate350  int    `json:"current_network_hashrate_350"`
		CurrentNetworkHashrate50   int    `json:"current_network_hashrate_50"`
		DaemonNetworkState         int    `json:"daemon_network_state"`
		DefaultFee                 int64  `json:"default_fee"`
		ExpirationMedianTimestamp  int    `json:"expiration_median_timestamp"`
		GreyPeerlistSize           int    `json:"grey_peerlist_size"`
		Height                     int    `json:"height"`
		IncomingConnectionsCount   int    `json:"incoming_connections_count"`
		IsHardfokActive            []bool `json:"is_hardfok_active"`
		LastBlockHash              string `json:"last_block_hash"`
		LastBlockSize              int    `json:"last_block_size"`
		LastBlockTimestamp         int    `json:"last_block_timestamp"`
		LastBlockTotalReward       int    `json:"last_block_total_reward"`
		LastPosTimestamp           int    `json:"last_pos_timestamp"`
		LastPowTimestamp           int    `json:"last_pow_timestamp"`
		MaxNetSeenHeight           int    `json:"max_net_seen_height"`
		Mi                         struct {
			BuildNo     int `json:"build_no"`
			Mode        int `json:"mode"`
			VerMajor    int `json:"ver_major"`
			VerMinor    int `json:"ver_minor"`
			VerRevision int `json:"ver_revision"`
		} `json:"mi"`
		MinimumFee               int64 `json:"minimum_fee"`
		NetTimeDeltaMedian       int   `json:"net_time_delta_median"`
		OffersCount              int   `json:"offers_count"`
		OutgoingConnectionsCount int   `json:"outgoing_connections_count"`
		OutsStat                 struct {
			Amount0       int `json:"amount_0"`
			Amount0001    int `json:"amount_0_001"`
			Amount001     int `json:"amount_0_01"`
			Amount01      int `json:"amount_0_1"`
			Amount1       int `json:"amount_1"`
			Amount10      int `json:"amount_10"`
			Amount100     int `json:"amount_100"`
			Amount1000    int `json:"amount_1000"`
			Amount10000   int `json:"amount_10000"`
			Amount100000  int `json:"amount_100000"`
			Amount1000000 int `json:"amount_1000000"`
		} `json:"outs_stat"`
		PerformanceData struct {
			AllTxsInsertTime5                                 int `json:"all_txs_insert_time_5"`
			BlockProcessingTime0                              int `json:"block_processing_time_0"`
			BlockProcessingTime1                              int `json:"block_processing_time_1"`
			EtcStuff6                                         int `json:"etc_stuff_6"`
			InsertTime4                                       int `json:"insert_time_4"`
			LonghashCalculatingTime3                          int `json:"longhash_calculating_time_3"`
			MapSize                                           int `json:"map_size"`
			RaiseBlockCoreEvent                               int `json:"raise_block_core_event"`
			TargetCalculatingCalc                             int `json:"target_calculating_calc"`
			TargetCalculatingEnumBlocks                       int `json:"target_calculating_enum_blocks"`
			TargetCalculatingTime2                            int `json:"target_calculating_time_2"`
			TxAddOneTxTime                                    int `json:"tx_add_one_tx_time"`
			TxAppendIsExpired                                 int `json:"tx_append_is_expired"`
			TxAppendRlWait                                    int `json:"tx_append_rl_wait"`
			TxAppendTime                                      int `json:"tx_append_time"`
			TxCheckExist                                      int `json:"tx_check_exist"`
			TxCheckInputsAttachmentCheck                      int `json:"tx_check_inputs_attachment_check"`
			TxCheckInputsLoop                                 int `json:"tx_check_inputs_loop"`
			TxCheckInputsLoopChInValSig                       int `json:"tx_check_inputs_loop_ch_in_val_sig"`
			TxCheckInputsLoopKimageCheck                      int `json:"tx_check_inputs_loop_kimage_check"`
			TxCheckInputsLoopScanOutputkeysGetItemSize        int `json:"tx_check_inputs_loop_scan_outputkeys_get_item_size"`
			TxCheckInputsLoopScanOutputkeysLoop               int `json:"tx_check_inputs_loop_scan_outputkeys_loop"`
			TxCheckInputsLoopScanOutputkeysLoopFindTx         int `json:"tx_check_inputs_loop_scan_outputkeys_loop_find_tx"`
			TxCheckInputsLoopScanOutputkeysLoopGetSubitem     int `json:"tx_check_inputs_loop_scan_outputkeys_loop_get_subitem"`
			TxCheckInputsLoopScanOutputkeysLoopHandleOutput   int `json:"tx_check_inputs_loop_scan_outputkeys_loop_handle_output"`
			TxCheckInputsLoopScanOutputkeysRelativeToAbsolute int `json:"tx_check_inputs_loop_scan_outputkeys_relative_to_absolute"`
			TxCheckInputsPrefixHash                           int `json:"tx_check_inputs_prefix_hash"`
			TxCheckInputsTime                                 int `json:"tx_check_inputs_time"`
			TxCount                                           int `json:"tx_count"`
			TxMixinCount                                      int `json:"tx_mixin_count"`
			TxPrapareAppend                                   int `json:"tx_prapare_append"`
			TxPrintLog                                        int `json:"tx_print_log"`
			TxProcessAttachment                               int `json:"tx_process_attachment"`
			TxProcessExtra                                    int `json:"tx_process_extra"`
			TxProcessInputs                                   int `json:"tx_process_inputs"`
			TxPushGlobalIndex                                 int `json:"tx_push_global_index"`
			TxStoreDb                                         int `json:"tx_store_db"`
			WriterTxCount                                     int `json:"writer_tx_count"`
		} `json:"performance_data"`
		PosAllowed                   bool   `json:"pos_allowed"`
		PosBlockTsShiftVsActual      int    `json:"pos_block_ts_shift_vs_actual"`
		PosDiffTotalCoinsRate        int    `json:"pos_diff_total_coins_rate"`
		PosDifficulty                string `json:"pos_difficulty"`
		PosSequenceFactor            int    `json:"pos_sequence_factor"`
		PowDifficulty                int64  `json:"pow_difficulty"`
		PowSequenceFactor            int    `json:"pow_sequence_factor"`
		SecondsFor10Blocks           int    `json:"seconds_for_10_blocks"`
		SecondsFor30Blocks           int    `json:"seconds_for_30_blocks"`
		Status                       string `json:"status"`
		SynchronizationStartHeight   int    `json:"synchronization_start_height"`
		SynchronizedConnectionsCount int    `json:"synchronized_connections_count"`
		TotalCoins                   string `json:"total_coins"`
		TransactionsCntPerDay        int    `json:"transactions_cnt_per_day"`
		TransactionsVolumePerDay     int    `json:"transactions_volume_per_day"`
		TxCount                      int    `json:"tx_count"`
		TxCountInLastBlock           int    `json:"tx_count_in_last_block"`
		TxPoolPerformanceData        struct {
			BeginTxTime                   int `json:"begin_tx_time"`
			CheckInputsTime               int `json:"check_inputs_time"`
			CheckInputsTypesSupportedTime int `json:"check_inputs_types_supported_time"`
			CheckKeyimagesWsMsTime        int `json:"check_keyimages_ws_ms_time"`
			DbCommitTime                  int `json:"db_commit_time"`
			ExpirationValidateTime        int `json:"expiration_validate_time"`
			TxProcessingTime              int `json:"tx_processing_time"`
			UpdateDbTime                  int `json:"update_db_time"`
			ValidateAliasTime             int `json:"validate_alias_time"`
			ValidateAmountTime            int `json:"validate_amount_time"`
		} `json:"tx_pool_performance_data"`
		TxPoolSize        int `json:"tx_pool_size"`
		WhitePeerlistSize int `json:"white_peerlist_size"`
	} `json:"result"`
}
