name: boxwallet
architectures:
  - build-on: [ amd64, armhf, arm64, i386 ]
summary: BoxWallet is a multi-coin CLI tool, that gets your wallet/node running fast!
description: |
  BoxWallet is a single binary multi-coin CLI tool, that gets your coin-of-choice wallet/node set-up fast with just a few commands:

  boxwallet coin - allows you to choose your coin of choice, which then downloads the projects core files from their official website and installs them automatically.

  boxwallet start - starts the coin's daemon, which syncs the Blockchain.

  boxwallet dash - displays a dashboard with the coins Blockchain and wallet info.
base: core18
version: "0.41.2"

parts:
  boxwallet:
    source: https://github.com/richardltc/boxwallet.git
    plugin: go

apps:
  boxwallet:
    command: cli
    plugs:
    - dot-bitcoinplus
    - dot-devault
    - dot-digibyte
    - dot-feathercoin
    - dot-groestlcoin
    - dot-phore
    - dot-pivx
    - dot-rapids
    - dot-reddcoin
    - dot-scala
    - dot-syscoin
    - dot-trezarcoin
    - dot-vertcoin

confinement: strict

plugs:
  dot-bitcoinplus:
    interface: personal-files
    write:
      - $HOME/.bitcoinplus
  dot-devault:
    interface: personal-files
    write:
      - $HOME/.devault
  dot-digibyte:
    interface: personal-files
    write:
      - $HOME/.digibyte
  dot-divi:
    interface: personal-files
    write:
      - $HOME/.divi
  dot-feathercoin:
    interface: personal-files
    write:
      - $HOME/.feathercoin
  dot-groestlcoin:
    interface: personal-files
    write:
      - $HOME/.groestlcoin
  dot-phore:
    interface: personal-files
    write:
      - $HOME/.phore
  dot-pivx:
    interface: personal-files
    write:
      - $HOME/.pivx
  dot-rapids:
    interface: personal-files
    write:
      - $HOME/.rapids
  dot-reddcoin:
    interface: personal-files
    write:
      - $HOME/.reddcoin
  dot-scala:
    interface: personal-files
    write:
      - $HOME/.scala
  dot-syscoin:
    interface: personal-files
    write:
      - $HOME/.syscoin
  dot-trezarcoin:
    interface: personal-files
    write:
      - $HOME/.trezarcoin
  dot-vertcoin:
    interface: personal-files
    write:
      - $HOME/.vertcoin
