name: boxwallet
architectures:
  - build-on: [ amd64, armhf, arm64, i386 ]
summary: BoxWallet is a multi-coin CLI tool, that gets your wallet/node running fast!
description: |
  BoxWallet is a single binary multi-coin CLI tool, that gets your coin-of-choice wallet/node set-up fast with just a few commands:

  boxwallet coin - allows you to choose your coin of choice, which then downloads the projects core files from their official website and installs them automatically.

  boxwallet start - starts the coin's daemon, which syncs the Blockchain.

  boxwallet dash - displays a dashboard with the coins Blockchain and wallet info.
base: core18
version: "0.40.5"

parts:
  boxwallet:
    source: https://github.com/richardltc/boxwallet.git
    plugin: go

apps:
  boxwallet:
    command: cli
    plugs: [ "personal-files" ]

confinement: strict

plugs:
  dot-divi:
    interface: personal-files
    read:
      - $HOME/.divi
    write:
      - $HOME/.divi

